import mongoose from "mongoose";

const CollegeSchema = new mongoose.Schema({
  fullName: String,
  shortName: String,
  kebabName: String,
  location: String,
  setting: String,
  campusSize: Number,
  genRanking: Number,
  programRankings: {
    bestValue: Number,
    engineering: Number,
    biomedEng: Number,
    eeEng: Number,
    mechEng: Number,
    compSci: Number,
    ai: Number,
    cyberSec: Number,
    dataScience: Number,
    writing: Number,
    studyAbroad: Number,
  },
  acceptanceRate: Number,
  numStudents: Number,
  public: Boolean,
  baseCost: Number,
  costAfterAid: Number,
  decisionMetrics: [String],
  suppEssays: [String],
  testRange: {
    "25thACT": Number,
    "50thACT": Number,
    "75thACT": Number,
    "25thSAT": Number,
    "50thSAT": Number,
    "75thSAT": Number,
  },
  gpaRange: {
    "25thWeighted": Number,
    "50thWeighted": Number,
    "75thWeighted": Number,
    "25thUnweighted": Number,
    "50thUnweighted": Number,
    "75thUnweighted": Number,
  },
  imgLinks: [String],
  deadlines: {
    earlyAction: Date,
    earlyDecision: Date,
    earlyDecision2: Date,
    earlyAid: Date,
    ed2Aid: Date,
    financialAid: Date,
    regularDecision: Date,
    rolling: Boolean,
  },
});

export const CollegeModel = mongoose.model("colleges", CollegeSchema);
