INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('Boston College', 'Boston College', 'boston-college', 'Chestnut Hill, MA', 'Suburban', 405, 36, 16.7, 9532, 64176, 36599, 'Private', 1350, 1410, 1480, 31, 33, 34);
-- Deadline 1 for Boston College
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Boston College'), 'regularDecision', '2024-01-03T00:00:00.000Z', 'Regular Decision', '2024-02-02T00:00:00.000Z');
-- Deadline 2 for Boston College
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Boston College'), 'earlyDecision', '2023-11-02T00:00:00.000Z', 'Early Decision I ', '2023-11-02T00:00:00.000Z');
-- Deadline 3 for Boston College
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Boston College'), 'earlyDecision2', '2024-01-03T00:00:00.000Z', 'Early Decision II', '2024-01-04T00:00:00.000Z');
-- Supplemental Essay 1 for Boston College
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Boston College'), '1. Each year at University Convocation, our incoming class engages in reflective dialogue with the author of a common text. What book by a living author would you recommend for your incoming class to read and why would this be an important shared text?', 400);
-- Supplemental Essay 2 for Boston College
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Boston College'), '2. At Boston College, we draw upon the Jesuit tradition of finding worthwhile conversation partners. Some support our viewpoints while others challenge them. Who fulfills this role in your life? Please cite a specific conversation you had where this conversation partner challenged your perspective or you challenged theirs.', 400);
-- Supplemental Essay 3 for Boston College
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Boston College'), '3. In her November 2019 Ted Talk, “The Danger of a Single Story,” Chimamanda Ngozi Adichi warned viewers against assigning people a “single story” through assumptions about their nationality, appearance, or background. Discuss a time when someone defined you by a single story. What challenges did this present and how did you overcome them?', 400);
-- Supplemental Essay 4 for Boston College
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Boston College'), '4. Boston College’s founding in 1863 was in response to society’s call. That call came from an immigrant community in Boston seeking a Jesuit education to foster social mobility. Still today, the University empowers its students to use their education to address society’s greatest needs. Which of today’s local or global issues is of particular concern to you and how might you use your Boston College education to address it?', 400);
-- Supplemental Essay 5 for Boston College
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Boston College'), '5. Human-Centered Engineering (HCE) Applicants only: One goal of a Jesuit education is to prepare students to serve the Common Good. Human-Centered Engineering at Boston College integrates technical knowledge, creativity, and a humanistic perspective to address societal challenges and opportunities. What societal problems are important to you and how will you use your HCE education to solve them?', 400);
