INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('California Institute of Technology', 'Caltech', 'caltech', 'Pasadena, CA', 'Suburban', 124, 9, 3.9, 987, 60864, 26542, 'Private', 0, 0, 0, 0, 0, 0);
-- Deadline 1 for California Institute of Technology
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'California Institute of Technology'), 'regularDecision', '2024-01-04T00:00:00.000Z', 'Regular Decision', '2024-03-17T00:00:00.000Z');
-- Deadline 2 for California Institute of Technology
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'California Institute of Technology'), 'earlyAction', '2023-11-02T00:00:00.000Z', 'Restrictive Early Action', '2023-12-15T00:00:00.000Z');
-- Supplemental Essay 1 for California Institute of Technology
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'California Institute of Technology'), 'If you had to choose an area of interest or two today, what would you choose? Why did you choose that interest?', 200);
-- Supplemental Essay 2 for California Institute of Technology
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'California Institute of Technology'), 'Identify and describe two STEM-related experiences from your high shcool years, either in or out of the classroom, and tell us why and how they activated your curiousity. What about them made you want to learn more and explore further?', 400);
-- Supplemental Essay 3 for California Institute of Technology
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'California Institute of Technology'), 'The creativity, inventiveness, and innovation of Caltech''s students, faculty, and researchers have won Nobel prizes and put rovers on Mars. But Techers also imagine smaller scale innovations every day, from new ways to design solar cells to how to 3D print dorm decor. How have you been a creator, inventor, or innovator in your own life?', 250);
-- Supplemental Essay 4 for California Institute of Technology
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'California Institute of Technology'), 'If there are aspects of your life or social or personal identity that you feel are not captured elsewhere in this application, please tell us about them below.', 150);
-- Supplemental Essay 5 for California Institute of Technology
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'California Institute of Technology'), 'When not surveying the stars, peering through microscopes, or running through marathons of coding, Caltech students pursue an eclectic array of interests that range from speed-cubing to participating in varsity athletics to reading romance novels. What is a favorite interest or hobby, and why does it bring you joy?', 100);
-- Supplemental Essay 6 for California Institute of Technology
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'California Institute of Technology'), 'Did you have a hard time narrowing it down to just one interest or hobby? We understand – Caltech students like to stay busy, too – tell us about another hobby or interest!', 50);
-- Supplemental Essay 7 for California Institute of Technology
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'California Institute of Technology'), 'Caltech''s mission – to cultivate learning, discovery, and innovation for the benefit of humanity – relies on its community members embracing our Mission-Based Values, which include: 
\n1. Openness and enthusiasm for having preconceptions challenged 
\n2. Respect and appreciation for the idea that, while we are all members of the same community, the opportunities we''ve had to develop, showcase, and apply our talents have not been equal 
\n3. Passion for the ideal that science can and should meaningfully improve the lives of others
\nShare what one or more of these values evokes for you.', 250);
