INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('Carnegie Mellon University', 'Carnegie Mellon', 'cmu', 'Pittsburgh, PA', 'Urban', 157, 22, 13.5, 7365, 61344, 36775, 'Private', 1500, 1540, 1560, 34, 35, 35);
-- Deadline 1 for Carnegie Mellon University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Carnegie Mellon University'), 'regularDecision', '2024-01-04T00:00:00.000Z', 'Regular Decision', '2024-02-16T00:00:00.000Z');
-- Deadline 2 for Carnegie Mellon University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Carnegie Mellon University'), 'earlyDecision', '2023-11-02T00:00:00.000Z', 'Early Decision 1', '2023-11-16T00:00:00.000Z');
-- Deadline 3 for Carnegie Mellon University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Carnegie Mellon University'), 'earlyDecision2', '2024-01-04T00:00:00.000Z', 'Early Decision 2', '2024-01-04T00:00:00.000Z');
-- Supplemental Essay 1 for Carnegie Mellon University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Carnegie Mellon University'), 'Most students choose their intended major or area of study based on a passion or inspiration that’s developed over time – what passion or inspiration led you to choose this area of study? (300 word maximum)', 300);
-- Supplemental Essay 2 for Carnegie Mellon University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Carnegie Mellon University'), 'Many students pursue college for a specific degree, career opportunity or personal goal. Whichever it may be, learning will be critical to achieve your ultimate goal. As you think ahead to the process of learning during your college years, how will you define a successful college experience? (300 word maximum)', 300);
-- Supplemental Essay 3 for Carnegie Mellon University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Carnegie Mellon University'), 'Consider your application as a whole. What do you personally want to emphasize about your application for the admission committee’s consideration? Highlight something that’s important to you or something you haven’t had a chance to share. Tell us, don’t show us (no websites please). (300 word maximum)', 300);
