INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('Duke University', 'Duke', 'duke', 'Durham, NC', 'Suburban', 8693, 10, 5.9, 6883, 63054, 32459, 'Private', 1490, 1520, 1560, 33, 34, 35);
-- Deadline 1 for Duke University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Duke University'), 'regularDecision', '2024-01-03T00:00:00.000Z', 'Regular Decision', '2024-02-02T00:00:00.000Z');
-- Deadline 2 for Duke University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Duke University'), 'earlyDecision', '2023-11-02T00:00:00.000Z', 'Early Decision', '2023-11-02T00:00:00.000Z');
-- Supplemental Essay 1 for Duke University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Duke University'), 'What is your sense of Duke as a university and a community, and why do you consider it a good match for you?  If there''s something in particular about our offerings that attracts you, feel free to share that as well. (250 word limit)', 250);
-- Supplemental Essay 2 for Duke University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Duke University'), '1. Perspective response: We believe a wide range of personal perspectives, beliefs, and lived experiences are essential to making Duke a vibrant and meaningful living and learning community. Feel free to share with us anything in this context that might help us better understand you and what you might bring to our community.', 250);
-- Supplemental Essay 3 for Duke University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Duke University'), '2. Intellectual experience: Tell us about an intellectual experience in the past two years that you found absolutely fascinating.', 250);
-- Supplemental Essay 4 for Duke University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Duke University'), '3. Beliefs & values: We believe there is benefit in sharing and sometimes questioning our beliefs or values; who do you agree with on the big important things, or who do you have your most interesting disagreements with? What are you agreeing or disagreeing about?', 250);
-- Supplemental Essay 5 for Duke University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Duke University'), '4. Being different: We recognize that “fitting in” in all the contexts we live in can sometimes be difficult. Duke values all kinds of differences and believes they make our community better. Feel free to tell us any ways in which you’re different, and how that has affected you or what it means to you.', 250);
-- Supplemental Essay 6 for Duke University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Duke University'), '5. Orientation, identity, expression: Duke’s commitment to inclusion and belonging includes sexual orientation, gender identity, and gender expression. Feel free to share with us more about how your identity in this context has meaning for you as an individual or as a member of a community.', 250);
