INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('Georgetown University', 'Georgetown', 'georgetown', 'Washington, DC', 'Urban', 104, 22, 12, 7598, 62052, 32108, 'Private', 1410, 1480, 1540, 32, 34, 35);
-- Deadline 1 for Georgetown University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Georgetown University'), 'regularDecision', '2024-01-11T00:00:00.000Z', 'Regular Decision', '2024-02-02T00:00:00.000Z');
-- Deadline 2 for Georgetown University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Georgetown University'), 'earlyAction', '2023-11-02T00:00:00.000Z', 'Early Action', '2023-02-02T00:00:00.000Z');
-- Supplemental Essay 1 for Georgetown University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Georgetown University'), 'As Georgetown is a diverse community, the Admissions Committee would like to know more about you in your own words. Please submit a brief personal or creative essay which you feel best describes you and reflects on your own background, identity, skills, and talents.', Unknown);
-- Supplemental Essay 2 for Georgetown University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Georgetown University'), 'A liberal arts education from the College of Arts & Sciences involves encounters with new concepts and modes of inquiry. Describe something (a class, a book, an event, etc.) that changed your thinking. (Applicants to the sciences, mathematics, public policy or languages are encouraged to include examples related to that field.)', Unknown);
