INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('George Washington University', 'GW University', 'gwu', 'Washington, DC', 'Urban', 43, 62, 49.7, 11482, 64990, 26272, 'Private', 1320, 1390, 1460, 30, 32, 34);
-- Deadline 1 for George Washington University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'George Washington University'), 'regularDecision', '2024-01-06T00:00:00.000Z', 'Regular Decision', '2024-01-06T00:00:00.000Z');
-- Deadline 2 for George Washington University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'George Washington University'), 'earlyDecision', '2023-11-02T00:00:00.000Z', 'Early Decision I', '2023-11-02T00:00:00.000Z');
-- Deadline 3 for George Washington University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'George Washington University'), 'earlyDecision2', '2024-01-06T00:00:00.000Z', 'Early Decision II ', '2024-01-06T00:00:00.000Z');
-- Supplemental Essay 1 for George Washington University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'George Washington University'), 'At the George Washington University, our students frequently interact with policymakers and world leaders. These experiences and those of our alumni can shape the future of global affairs. If you had the power to change the course of history in your community or the world, what would you do and why? ', 500);
-- Supplemental Essay 2 for George Washington University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'George Washington University'), 'The George Washington University encourages students to think critically and to challenge the status quo. Thus, civil discourse is a key characteristic of our community. Describe a time when you engaged others in meaningful dialogue around an issue that was important to you. Did this exchange create change, new perspectives, or deeper relationships?', 500);
