INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('Johns Hopkins University', 'Johns Hopkins', 'jhu', 'Baltimore, MD', 'Urban', 140, 7, 7.5, 6132, 60480, 23428, 'Private', 1520, 1540, 1560, 34, 35, 35);
-- Deadline 1 for Johns Hopkins University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Johns Hopkins University'), 'regularDecision', '2024-01-03T00:00:00.000Z', 'Regular Decision', '2024-01-16T00:00:00.000Z');
-- Deadline 2 for Johns Hopkins University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Johns Hopkins University'), 'earlyDecision', '2023-11-02T00:00:00.000Z', 'Early Decision I', '2023-11-16T00:00:00.000Z');
-- Deadline 3 for Johns Hopkins University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Johns Hopkins University'), 'earlyDecision2', '2024-01-03T00:00:00.000Z', 'Early Decision II', '2024-01-16T00:00:00.000Z');
-- Supplemental Essay 1 for Johns Hopkins University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Johns Hopkins University'), 'Tell us about an aspect of your identity (e.g. race, gender, sexuality, religion, community, etc.) or a life experience that has shaped you as an individual and how that influenced what you’d like to pursue in college at Hopkins.? (This can be a future goal or experience that is either academic, extracurricular, or social). 300 word limit.', 300);
