INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('Massachusetts Institute of Technology', 'MIT', 'mit', 'Cambridge, MA', 'Urban', 168, 2, 4.1, 4638, 57986, 16407, 'Private', 1510, 1530, 1570, 34, 35, 36);
-- Deadline 1 for Massachusetts Institute of Technology
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Massachusetts Institute of Technology'), 'regularDecision', '2024-01-06T00:00:00.000Z', 'Regular Action', '2024-02-16T00:00:00.000Z');
-- Deadline 2 for Massachusetts Institute of Technology
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Massachusetts Institute of Technology'), 'earlyAction', '2023-11-02T00:00:00.000Z', 'Early Action', '2023-12-01T00:00:00.000Z');
-- Supplemental Essay 1 for Massachusetts Institute of Technology
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Massachusetts Institute of Technology'), 'We know you lead a busy life, full of activities, many of which are required of you. Tell us about something you do simply for the pleasure of it.', 200);
-- Supplemental Essay 2 for Massachusetts Institute of Technology
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Massachusetts Institute of Technology'), 'Describe the world you come from (for example, your family, school, community, city, or town). How has that world shaped your dreams and aspirations?', 200);
-- Supplemental Essay 3 for Massachusetts Institute of Technology
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Massachusetts Institute of Technology'), 'MIT brings people with diverse backgrounds and experiences together to better the lives of others. Our students work to improve their communities in different ways, from tackling the world’s biggest challenges to being a good friend. Describe one way you have collaborated with people who are different from you to contribute to your community.', 200);
-- Supplemental Essay 4 for Massachusetts Institute of Technology
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Massachusetts Institute of Technology'), 'Tell us about a significant challenge you’ve faced (that you feel comfortable sharing) or something that didn’t go according to plan. How did you manage the situation?', 200);
