INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('North Carolina State University', 'NC State', 'ncsu', 'Raleigh, NC', 'Urban', 2140, 60, 47.5, 26254, 20488, 16239, 'Public', 1260, 1340, 1420, 24, 28, 31);
-- Deadline 1 for North Carolina State University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'North Carolina State University'), 'regularDecision', '2024-01-16T00:00:00.000Z', 'Regular Decision', '2024-03-02T00:00:00.000Z');
-- Deadline 2 for North Carolina State University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'North Carolina State University'), 'earlyAction', '2023-11-02T00:00:00.000Z', 'Early Action', '2024-03-02T00:00:00.000Z');
-- Supplemental Essay 1 for North Carolina State University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'North Carolina State University'), 'Discuss any other obstacles and/or hardships that you have encountered that have affected you personally or academically and how you dealt with them.', 250);
-- Supplemental Essay 2 for North Carolina State University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'North Carolina State University'), 'Explain why you selected the academic program(s) above and why you are interested in studying these at NC State.', 250);
