INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('Princeton University', 'Princeton', 'princeton', 'Princeton, NJ', 'Suburban', 600, 1, 4.4, 5321, 57410, 9836, 'Private', 1510, 1540, 1570, 34, 35, 35);
-- Deadline 1 for Princeton University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Princeton University'), 'regularDecision', '2024-01-02T00:00:00.000Z', 'Regular Decision', '2024-02-02T00:00:00.000Z');
-- Deadline 2 for Princeton University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Princeton University'), 'earlyAction', '2023-11-02T00:00:00.000Z', 'Single-Choice Early Action', '2023-11-10T00:00:00.000Z');
-- Supplemental Essay 1 for Princeton University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Princeton University'), 'Princeton values community and encourages students, faculty, staff and leadership to engage in respectful conversations that can expand their perspectives and challenge their ideas and beliefs. As a prospective member of this community, reflect on how your lived experiences will impact the conversations you will have in the classroom, the dining hall or other campus spaces. What lessons have you learned in life thus far? What will your classmates learn from you? In short, how has your lived experience shaped you? (500 words or fewer)', 500);
-- Supplemental Essay 2 for Princeton University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Princeton University'), 'Princeton has a longstanding commitment to understanding our responsibility to society through service and civic engagement. How does your own story intersect with these ideals? (250 words or fewer)', 250);
-- Supplemental Essay 3 for Princeton University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Princeton University'), 'What is a new skill you would like to learn in college? (50 words or fewer)', 50);
-- Supplemental Essay 4 for Princeton University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Princeton University'), 'What brings you joy? (50 words or fewer)', 50);
-- Supplemental Essay 5 for Princeton University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Princeton University'), 'What song represents the soundtrack of your life at this moment? (50 words or fewer)', 50);
