INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('Santa Clara University', 'Santa Clara', 'santa-clara', 'Santa Clara, CA', 'City', 106, 55, 54, 6115, 59241, 43228, 'Private', 1300, 1390, 1470, 29, 31, 33);
-- Deadline 1 for Santa Clara University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Santa Clara University'), 'regularDecision', '2024-01-08T00:00:00.000Z', 'Regular Decision', '2024-02-02T00:00:00.000Z');
-- Deadline 2 for Santa Clara University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Santa Clara University'), 'earlyAction', '2023-11-02T00:00:00.000Z', 'Early Action', '2023-11-16T00:00:00.000Z');
-- Deadline 3 for Santa Clara University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Santa Clara University'), 'earlyDecision', '2023-11-02T00:00:00.000Z', 'Early Decision I', '2023-11-16T00:00:00.000Z');
-- Deadline 4 for Santa Clara University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Santa Clara University'), 'earlyDecision2', '2024-01-08T00:00:00.000Z', 'Early Decision II', '2024-01-16T00:00:00.000Z');
-- Supplemental Essay 1 for Santa Clara University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Santa Clara University'), 'At Santa Clara University, we value our diverse and inclusive community. Our campus learning environment is enriched by the lived experiences of people from different backgrounds. What people, places, events, or circumstances have shaped the individual you are today and how you could contribute to our community? (150- 300 words)', 300);
-- Supplemental Essay 2 for Santa Clara University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Santa Clara University'), 'At Santa Clara University, we push our students to be creative, be challenged, and be the solution. Think about an ethical dilemma that you care about that our society is currently facing. This can be something happening in your local community or more globally. How can an SCU education help you prepare for and address this challenge? (150- 300 words)', 300);
