INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('Syracuse University', 'Syracuse', 'syracuse', 'Syracuse, NY', 'City', 721, 62, 59.2, 15421, 63061, 32516, 'Private', 1260, 1340, 1410, 28, 30, 32);
-- Deadline 1 for Syracuse University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Syracuse University'), 'regularDecision', '2024-01-06T00:00:00.000Z', 'Regular Decision', '2024-01-06T00:00:00.000Z');
-- Deadline 2 for Syracuse University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Syracuse University'), 'earlyDecision', '2023-11-16T00:00:00.000Z', 'Early Decision', '2023-11-16T00:00:00.000Z');
-- Deadline 3 for Syracuse University
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Syracuse University'), 'earlyDecision2', '2024-01-06T00:00:00.000Z', 'Early Decision II', '2024-01-06T00:00:00.000Z');
-- Supplemental Essay 1 for Syracuse University
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'Syracuse University'), 'Syracuse University is a place that seeks to be welcoming to all – and has been since our founding. Explain why you are interested in Syracuse University and describe a personal experience in which you persevered through adversity, rejected discrimination, learned a lesson, or were inspired by the courageous actions of others and how you will apply what you learned to our community in a positive way.', 250);
