INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('University of Chicago', 'UChicago', 'uchicago', 'Chicago, IL', 'Urban', 217, 6, 6.5, 7526, 62940, 28517, 'Private', 1510, 1530, 1560, 33, 34, 35);
-- Deadline 1 for University of Chicago
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Chicago'), 'regularDecision', '2024-01-03T00:00:00.000Z', 'Regular Decision', '2024-02-16T00:00:00.000Z');
-- Deadline 2 for University of Chicago
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Chicago'), 'earlyAction', '2023-11-02T00:00:00.000Z', 'Early Action', '2023-11-16T00:00:00.000Z');
-- Deadline 3 for University of Chicago
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Chicago'), 'earlyDecision', '2023-11-02T00:00:00.000Z', 'Early Decision I', '2023-11-16T00:00:00.000Z');
-- Deadline 4 for University of Chicago
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Chicago'), 'earlyDecision2', '2024-01-03T00:00:00.000Z', 'Early Decision II ', '2024-01-16T00:00:00.000Z');
-- Supplemental Essay 1 for University of Chicago
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Chicago'), '1. Exponents and square roots, pencils and erasers, beta decay and electron capture. Name two things that undo each other and explain why both are necessary.', 1000);
-- Supplemental Essay 2 for University of Chicago
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Chicago'), '2. “Where have all the flowers gone?” – Pete Seeger. Pick a question from a song title or lyric and give it your best answer. ', 1000);
-- Supplemental Essay 3 for University of Chicago
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Chicago'), '3. “Vlog,” “Labradoodle,” and “Fauxmage.” Language is filled with portmanteaus. Create a new portmanteau and explain why those two things are a “patch” (perfect match). ', 1000);
-- Supplemental Essay 4 for University of Chicago
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Chicago'), '4. A jellyfish is not a fish. Cat burglars don’t burgle cats. Rhode Island is not an island. Write an essay about some other misnomer, and either come up with and defend a new name for it or explain why its inaccurate name should be kept. ', 1000);
-- Supplemental Essay 5 for University of Chicago
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Chicago'), '5. Despite their origins in the Gupta Empire of India or Ancient Egypt, games like chess or bowling remain widely enjoyed today. What modern game do you believe will withstand the test of time, and why?', 1000);
-- Supplemental Essay 6 for University of Chicago
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Chicago'), '6. There are unwritten rules that everyone follows or has heard at least once in their life. But of course, some rules should be broken or updated. What is an unwritten rule that you wish didn’t exist? (Our custom is to have five new prompts each year, but this year we decided to break with tradition. Enjoy!)  ', 1000);
-- Supplemental Essay 7 for University of Chicago
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Chicago'), '7. And, as always… the classic choose your own adventure option! In the spirit of adventurous inquiry, choose one of our past prompts (or create a question of your own). Be original, creative, thought provoking. Draw on your best qualities as a writer, thinker, visionary, social critic, sage, citizen of the world, or future citizen of the University of Chicago; take a little risk, and have fun!', 1000);
