INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('University of California, Irvine', 'UC Irvine', 'ucirvine', 'Irvine, CA', 'Suburban', 1475, 34, 28.8, 29449, 43739, 12209, 'Public', 0, 0, 0, 0, 0, 0);
-- Deadline 1 for University of California, Irvine
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of California, Irvine'), 'regularDecision', '2023-12-02T00:00:00.000Z', 'Regular Decision', '2024-01-02T00:00:00.000Z');
-- Supplemental Essay 1 for University of California, Irvine
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of California, Irvine'), '1. Describe an example of your leadership experience in which you have positively influenced others, helped resolve disputes or contributed to group efforts over time.', 350);
-- Supplemental Essay 2 for University of California, Irvine
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of California, Irvine'), '2. Every person has a creative side, and it can be expressed in many ways: problem solving, original and innovative thinking, and artistically, to name a few. Describe how you express your creative side.', 350);
-- Supplemental Essay 3 for University of California, Irvine
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of California, Irvine'), '3. What would you say is your greatest talent or skill? How have you developed and demonstrated that talent over time?', 350);
-- Supplemental Essay 4 for University of California, Irvine
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of California, Irvine'), '4. Describe how you have taken advantage of a significant educational opportunity or worked to overcome an educational barrier you have faced.', 350);
-- Supplemental Essay 5 for University of California, Irvine
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of California, Irvine'), '5. Describe the most significant challenge you have faced and the steps you have taken to overcome this challenge. How has this challenge affected your academic achievement?', 350);
-- Supplemental Essay 6 for University of California, Irvine
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of California, Irvine'), '6. Think about an academic subject that inspires you. Describe how you have furthered this interest inside and/or outside of the classroom.', 350);
-- Supplemental Essay 7 for University of California, Irvine
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of California, Irvine'), '7. What have you done to make your school or your community a better place?', 350);
-- Supplemental Essay 8 for University of California, Irvine
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of California, Irvine'), '8. Beyond what has already been shared in your application, what do you believe makes you a strong candidate for admissions to the University of California?', 350);
