INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('University of Illinois Urbana-Champaign', 'UIUC', 'uiuc', 'Champaign, IL', 'City', 1783, 41, 59.7, 34779, 35110, 14321, 'Public', null, null, null, null, null, null);
-- Deadline 1 for University of Illinois Urbana-Champaign
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Illinois Urbana-Champaign'), 'regularDecision', '2024-01-06T00:00:00.000Z', 'Regular Decision', '2024-03-16T00:00:00.000Z');
-- Deadline 2 for University of Illinois Urbana-Champaign
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Illinois Urbana-Champaign'), 'earlyAction', '2023-11-02T00:00:00.000Z', 'Early Action', '2024-02-02T00:00:00.000Z');
-- Supplemental Essay 1 for University of Illinois Urbana-Champaign
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Illinois Urbana-Champaign'), 'Explain, in detail, an experience you''ve had in the past 3 to 4 years related to your first-choice major. This can be an experience from an extracurricular activity, in a class you’ve taken, or through something else.', 150);
-- Supplemental Essay 2 for University of Illinois Urbana-Champaign
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Illinois Urbana-Champaign'), 'Describe your personal and/or career goals after graduating from UIUC and how your selected first-choice major will help you achieve them.', 150);
