INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('University of Michigan - Ann Arbor', 'UMich - Ann Arbor', 'umich', 'Ann Arbor, MI', 'City', 3177, 25, 20.2, 32282, 57273, 14878, 'Public', 1350, 1470, 1530, 31, 33, 34);
-- Deadline 1 for University of Michigan - Ann Arbor
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Michigan - Ann Arbor'), 'regularDecision', '2024-01-02T00:00:00.000Z', 'Regular Decision', '2024-04-01T00:00:00.000Z');
-- Deadline 2 for University of Michigan - Ann Arbor
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Michigan - Ann Arbor'), 'earlyAction', '2023-11-02T00:00:00.000Z', 'Early Action', '2023-12-16T00:00:00.000Z');
-- Supplemental Essay 1 for University of Michigan - Ann Arbor
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Michigan - Ann Arbor'), 'Everyone belongs to many different communities and/or groups defined by (among other things) shared geography, religion, ethnicity, income, cuisine, interest, race, ideology, or intellectual heritage. Choose one of the communities to which you belong, and describe that community and your place within it. ', 300);
-- Supplemental Essay 2 for University of Michigan - Ann Arbor
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Michigan - Ann Arbor'), 'Describe the unique qualities that attract you to the specific undergraduate College or School (including preferred admission and dual degree programs) to which you are applying at the University of Michigan. How would that curriculum support your interests?', 550);
