INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('University of North Carolina at Chapel Hill', 'UNC Chapel Hill', 'unc', 'Chapel Hill, NC', 'Suburban', 729, 29, 20.4, 19897, 37558, 12469, 'Public', 1330, 1420, 1500, 29, 31, 33);
-- Deadline 1 for University of North Carolina at Chapel Hill
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of North Carolina at Chapel Hill'), 'regularDecision', '2024-01-16T00:00:00.000Z', 'Regular Decision', '2024-03-02T00:00:00.000Z');
-- Deadline 2 for University of North Carolina at Chapel Hill
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of North Carolina at Chapel Hill'), 'earlyAction', '2023-10-16T00:00:00.000Z', 'Early Action (Non-Binding)', '2024-03-02T00:00:00.000Z');
-- Supplemental Essay 1 for University of North Carolina at Chapel Hill
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of North Carolina at Chapel Hill'), 'Prompt #1: Discuss one of your personal qualities and share a story, anecdote, or memory of how it helped you make a positive impact on a community. This could be your current community or another community you have engaged. ', 250);
-- Supplemental Essay 2 for University of North Carolina at Chapel Hill
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of North Carolina at Chapel Hill'), 'Prompt #2: Discuss an academic topic that you’re excited to explore and learn more about in college. Why does this topic interest you? Topics could be a specific course of study, research interests, or any other area related to your academic experience in college. ', 250);
