INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('University of Pennsylvania', 'UPenn', 'upenn', 'Philadelphia, PA', 'Urban', 299, 7, 5.9, 9962, 63452, 25046, 'Private', 1500, 1540, 1570, 34, 35, 35);
-- Deadline 1 for University of Pennsylvania
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Pennsylvania'), 'regularDecision', '2024-01-06T00:00:00.000Z', 'Regular Decision', '2024-04-16T00:00:00.000Z');
-- Deadline 2 for University of Pennsylvania
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Pennsylvania'), 'earlyDecision', '2023-11-02T00:00:00.000Z', 'Early Decision', '2024-04-16T00:00:00.000Z');
-- Supplemental Essay 1 for University of Pennsylvania
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Pennsylvania'), 'Write a short thank-you note to someone you have not yet thanked and would like to acknowledge. (We encourage you to share this note with that person, if possible, and reflect on the experience!) (150-200 words)', 200);
-- Supplemental Essay 2 for University of Pennsylvania
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Pennsylvania'), 'How will you explore community at Penn? Consider how Penn will help shape your perspective, and how your experiences and perspective will help shape Penn. (150-200 words)', 200);
