INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('University of Rochester', 'URochester', 'urochester', 'Rochester, NY', 'Urban', 707, 36, 40.5, 6570, 61678, 31340, 'Private', 1410, 1460, 1520, 31, 33, 34);
-- Deadline 1 for University of Rochester
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Rochester'), 'regularDecision', '2024-01-06T00:00:00.000Z', 'Regular Decision', '2024-02-16T00:00:00.000Z');
-- Deadline 2 for University of Rochester
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Rochester'), 'earlyDecision', '2023-11-02T00:00:00.000Z', 'Early Decision I', '2023-12-02T00:00:00.000Z');
-- Deadline 3 for University of Rochester
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Rochester'), 'earlyDecision2', '2024-01-06T00:00:00.000Z', 'Early Decision II', '2024-02-16T00:00:00.000Z');
-- Supplemental Essay 1 for University of Rochester
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Rochester'), 'The University of Rochester motto of Meliora – or “ever better” - deeply integrates critical core values into all that we do. These core values of equity, leadership, integrity, openness, respect and accountability define not only who we are, but also who we hope to become. Please use the space below to highlight a time, creative idea or research experience when you put into action one or more of these characteristics in order to make yourself, your community or the world ever better. (250 word limit)', 250);
-- Supplemental Essay 2 for University of Rochester
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Rochester'), 'American social reformer, abolitionist, writer and statesman Frederick Douglass said, “Some know the value of education by having it. I knew its value by not having it.” Explain ways in which your background, educational experience, and opportunities have directly influenced you and your ability to do good in the world. What specific moments of growth, lessons learned and resilience in your life have prepared you to promote positive change for your community and the world?', 200);
-- Supplemental Essay 3 for University of Rochester
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Rochester'), 'Dr. Donna Strickland, University of Rochester alum and 2018 Nobel Prize winner in Physics said, “There’s no point in me being anything other than me.” The University of Rochester encourages each student to embrace the intersectionality of their identity and create their own individual curricular path and experience. What qualities and experiences make you the best version of yourself? What unique elements of your background, perspectives, and experiences will you bring to our community?', 200);
-- Supplemental Essay 4 for University of Rochester
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Rochester'), 'Susan B. Anthony, champion of abolition and women’s rights, once said “Organize, agitate, educate must be our war cry.” As you look to join our community of doers and disruptors, in what ways do you envision using both the curricular flexibility and co-curricular opportunities to invoke change for marginalized groups? How has your unique lived experience shaped you and prepared you to be a changemaker here?', 200);
-- Supplemental Essay 5 for University of Rochester
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Rochester'), 'The University of Rochester benefactor, entrepreneur, photography pioneer and philanthropist George Eastman said, “What we do during our working hours determines what we have; what we do in our leisure hours determines what we are.” How have the ways you''ve spent your time enabled you to grow as a person? What challenges have helped define you and your role within your many communities?', 200);
