INSERT INTO colleges (full_name, short_name, kebab_name, location, setting, campus_size, gen_ranking, acceptance_rate, num_students, base_cost, cost_after_aid, privacy, sat_25th_percentile, sat_50th_percentile, sat_75th_percentile, act_25th_percentile, act_50th_percentile, act_75th_percentile) VALUES ('University of Texas at Austin', 'UT Austin', 'ut-austin', 'Austin, TX', 'Urban', 431, 38, 28.7, 40916, 40996, 18350, 'Public', 1230, 1350, 1480, 27, 30, 33);
-- Deadline 1 for University of Texas at Austin
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Texas at Austin'), 'regularDecision', '2023-12-02T00:00:00.000Z', 'Regular Decision', '2024-03-16T00:00:00.000Z');
-- Deadline 2 for University of Texas at Austin
INSERT INTO deadlines (id, college_id, decision_type, date, special_name, financial_aid_deadline) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Texas at Austin'), 'earlyAction', '2023-11-02T00:00:00.000Z', 'Priority Deadline', '2024-01-03T00:00:00.000Z');
-- Supplemental Essay 1 for University of Texas at Austin
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Texas at Austin'), 'Why are you interested in the major you indicated as your first-choice major?  Please limit your response to 250-300 words.', 300);
-- Supplemental Essay 2 for University of Texas at Austin
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Texas at Austin'), 'Describe how your experiences, perspectives, talents, and/or your involvement in leadership activities (at your school, job, community, or within your family) will help you to make an impact both in and out of the classroom while enrolled at UT.  Please limit your response to 250-300 words.', 300);
-- Supplemental Essay 3 for University of Texas at Austin
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Texas at Austin'), 'The core purpose of The University of Texas at Austin is, To Transform Lives for the Benefit of Society. Please share how you believe your experience at UT-Austin will prepare you to Change the World after you graduate.  Please limit your response to 250-300 words.', 300);
-- Supplemental Essay 4 for University of Texas at Austin
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Texas at Austin'), 'Please share background on events or special circumstances that you feel may have impacted your high school academic performance.  If your response to this question is similar to one of the Common App Personal Essays, feel free to simply copy and paste the important parts of your essay here.   Please limit your response to 250-300 words.', 300);
-- Supplemental Essay 5 for University of Texas at Austin
INSERT INTO supplemental_essays (id, college_id, prompt, word_limit) VALUES (gen_random_uuid(), (SELECT id FROM colleges WHERE full_name = 'University of Texas at Austin'), 'Tell us your story. What unique opportunities or challenges have you experienced throughout your high school career that have shaped who you are today?  Please keep your essay between 500–700 words (typically two to three paragraphs).', 700);
